FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm test

RUN npm run build
# Pour api-gateway et commands-service
RUN apk add --no-cache curl
# Pour commands-service seulement
RUN apk add --no-cache postgresql-client


CMD ["node", "dist/server.js"]
