FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install && \
	npm install --save-dev @types/cors && \
	npm install cors

COPY . .

RUN npm run build && \
	apk add --no-cache curl postgresql-client

CMD ["node", "dist/server.js"]
